<?php

namespace Dreams\CommentaryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaryRepository extends EntityRepository
{
}
