<?php

namespace Dreams\DreamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DreamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DreamRepository extends EntityRepository {



}
