dreams_dream_show:
  pattern: /
  defaults: { _controller: DreamsDreamBundle:Dream:show }

dreams_dream_create:
  pattern: /dream/create
  defaults: { _controller: DreamsDreamBundle:Dream:create }

dreams_dream_mylist:
  pattern: /dream/mylist
  defaults: { _controller: DreamsDreamBundle:Dream:mylist }

dreams_dream_edit:
  pattern: /dream/edit/{id}
  defaults: { _controller: DreamsDreamBundle:Dream:edit }

dreams_dream_vote:
  pattern: /dream/vote
  defaults: { _controller: DreamsDreamBundle:Dream:vote }

dreams_dream_delete:
  pattern: /dream/delete/{id}
  defaults: { _controller: DreamsDreamBundle:Dream:delete }

dreams_dream_search:
  pattern: /dream/search/
  defaults: { _controller: DreamsDreamBundle:Dream:search }