parameters:
#    dreams_commentary.example.class: Dreams\CommentaryBundle\Example

services:
#    dreams_commentary.example:
#        class: %dreams_commentary.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
