<?php

namespace Dreams\CommentBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Dreams\UserBundle\Entity\User;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{

    public function createComment(Comment $comment, User $user = null, Comment $answerTo = null){
                $comment->setUser($user);
                $comment->setAnswerTo($answerTo);
                //on ajoute le commentaire dans la BDD
                $em = $this->getEntityManager();
                $em->persist($comment);
                $em->flush();
    }

}
