<?php

namespace Dreams\CommentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VoteCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteCommentRepository extends EntityRepository {

}
